// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3602.DinkyBot.subsystems;

import org.usfirst.frc3602.DinkyBot.RobotMap;
import org.usfirst.frc3602.DinkyBot.commands.*;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftRearMotor = RobotMap.driveTrainLeftRearMotor;
    private final SpeedController leftFrontMotor = RobotMap.driveTrainLeftFrontMotor;
    private final SpeedController rightFrontMotor = RobotMap.driveTrainRightFrontMotor;
    private final SpeedController rightRearMotor = RobotMap.driveTrainRightRearMotor;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    private final AnalogInput gearSonar = RobotMap.driveTrainGearSonar;
    private double sonarDistance;
    private final AHRS gyro = RobotMap.gyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public DriveTrain() {
    	gearSonar.setAverageBits(16);
    	
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new driveWithJoystick());
    }
    
    public void manualDrive(Joystick joy) {
    	robotDrive.arcadeDrive(joy.getRawAxis(1), -joy.getRawAxis(2));
    }
    
    public void manualArcade(double move, double turn){
    	robotDrive.arcadeDrive(move, turn);
    }
    
    public double getGyroAngle() {
    	return gyro.getAngle();
    }
    
    public void reset() {
    	gyro.zeroYaw();
    }
    
    public void setDrive(double leftValue, double rightValue) {
    	robotDrive.tankDrive(leftValue, rightValue);
    }
    
    public void stop() {
    	robotDrive.stopMotor();
    }
    
    public void log() {
    	SmartDashboard.putNumber("Gyro Angle", getGyroAngle());
    }
}

