// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3602.DinkyBot;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Relay;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;

import com.ctre.CANTalon;
import com.ctre.CANTalon.FeedbackDevice;
import com.kauailabs.navx.frc.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftRearMotor;
    public static SpeedController driveTrainLeftFrontMotor;
    public static SpeedController driveTrainRightFrontMotor;
    public static SpeedController driveTrainRightRearMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static SpeedController shooterFeederVictor;
    public static SpeedController feederFeederSpark;
    public static SpeedController pickupPickupVictor;
    public static Encoder shooterShooterEncoder;
    public static AHRS gyro;
    public static AnalogInput driveTrainGearSonar;
    public static Relay lightSwitch;
    public static Servo linear;
    public static CANTalon shooterMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    


    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftRearMotor = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "LeftRearMotor", (Talon) driveTrainLeftRearMotor);
        
        driveTrainLeftFrontMotor = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "LeftFrontMotor", (Talon) driveTrainLeftFrontMotor);
        
        driveTrainRightFrontMotor = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "RightFrontMotor", (Talon) driveTrainRightFrontMotor);
        
        driveTrainRightRearMotor = new Talon(1);
        LiveWindow.addActuator("DriveTrain", "RightRearMotor", (Talon) driveTrainRightRearMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRightRearMotor);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        shooterFeederVictor = new Victor(4);
       
        gyro = new AHRS(SPI.Port.kMXP);
        
        linear = new Servo(7);
        linear.setBounds(2, 0, 0, 0, 1);
        
        
        shooterMotor = new CANTalon(5);
        shooterMotor.setFeedbackDevice(FeedbackDevice.CtreMagEncoder_Relative);
        shooterMotor.reverseSensor(false);
        shooterMotor.configNominalOutputVoltage(+0.0f, -0.0f);
        shooterMotor.configPeakOutputVoltage(+12.0f, -12.0f);
        shooterMotor.setProfile(0);
        shooterMotor.setF(0.027);
        shooterMotor.setP(0.05);
        shooterMotor.setI(0);
        		

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
